# Generated by Django 5.1 on 2024-10-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_facture_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='est_payee',
            field=models.BooleanField(default=False),
        ),
    ]
